# .github/workflows/merge-upstream.yml
name: merge upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0-4"   # 月〜金 JST 08:00

jobs:
  merge_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Git author
        run: |
          git config user.name  "your-app[bot]"
          git config user.email "your-app[bot]@users.noreply.github.com"

      - name: Add upstream & fetch
        run: |
          set -eux
          git remote add upstream "https://github.com/redmine/redmine.git" || true
          git fetch upstream master --prune

      - name: Merge upstream/master into master
        run: |
          set -eux
          git checkout master
          git merge upstream/master

      - name: Push
        run: |
          set -eux
          git push origin HEAD:master
