# .github/workflows/mirror-upstream-branch-and-tags.yml
name: Mirror upstream (branch + tags)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0-4' # 月-金 JST 08:00

permissions:
  contents: write
  checks: write

env:
  UPSTREAM_REPO: redmine/redmine
  UPSTREAM_BRANCH: master
  TARGET_BRANCH: master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no new commits are created)
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Add remotes & fetch
        run: |
          set -eux
          git remote add upstream "https://github.com/${UPSTREAM_REPO}.git"
          git fetch --prune upstream --tags

      - name: Hard reset target branch to upstream
        run: |
          set -eux
          git checkout "${TARGET_BRANCH}"
          git reset --hard "upstream/${UPSTREAM_BRANCH}"

      - name: Force push branch
        run: |
          set -eux
          git push origin "${TARGET_BRANCH}" --force-with-lease

      - name: Push all upstream tags
        run: |
          set -eux
          git push origin --tags --force
